# Generated by Django 3.2.15 on 2023-06-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20230626_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostModel',
            new_name='NewsModel',
        ),
    ]
